apiVersion: v1
kind: Service
metadata:
  name: solace-agent-mesh-svc
  namespace: sam-infra
spec:
  type: LoadBalancer
  selector:
    app: solace-agent-mesh
  ports:
    - name: sam-webui
      protocol: TCP
      port: 8000           # external port
      targetPort: 8000     # pod container port
    - name: broker-admin
      protocol: TCP
      port: 8008           # external port
      targetPort: 8008     # pod container port
  sessionAffinity: None
  externalTrafficPolicy: Cluster